# https://stackoverflow.com/questions/43322033/create-database-on-docker-compose-startup
version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./scripts/sql-init.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
